- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t java-Java-Petstore-Application-application .
      args:
        chdir: /var/lib/jenkins/workspace/java-Java-Petstore-Application-application

    - name: tag image
      command: docker tag Java-Petstore-Application:latest nomana29/Java-Petstore-Application:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: nomana29
        password: dckr_pat_rQleA95Qdb4tineHjAnA7EQzB_Q

    - name: Push image
      command: docker push nomana29/Java-Petstore-Application:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 nomana29/Java-Petstore-Application:latest
